name: Vehicles
version: '${project.version}'
main: me.swipez.vehicles.VehiclesPlugin
api-version: 1.19
authors: [ notnotnotswipez ]
commands:
  vehicle:
    description: A test command
  creationmode:
    description: A test command
  armorstandify:
    description: A test command